[testenv]
commands=
    pip install -e .
    pip install "flask{env:FLASK_VERSION:}" "werkzeug{env:FLASK_VERSION:}"
    pytest -p no:logging --cov=flask_socketio --cov-branch --cov-report=term-missing --cov-report=xml
deps=
    pytest
    pytest-cov
    redis

[testenv:flake8]
commands=
    flake8 --exclude=".*" --ignore=W503,E402,E722 src/flask_socketio test_socketio.py
deps=
    flake8

[testenv:docs]
changedir=docs
deps=
    sphinx
    furo
allowlist_externals=
    make
commands=
    make html
