name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox tox-gh-actions
      - run: tox -eflake8
      - run: tox -edocs
  tests:
    name: tests
    strategy:
      matrix:
        flask: ['<2.2', '<3.0', '<3.1', '<3.2', '']
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.10', '3.11', '3.12', '3.13', '3.14', 'pypy-3.11']
        exclude:
          - flask: '<2.2'
            python: '3.14'
          - flask: '<2.2'
            os: macos-latest
          - flask: '<3.0'
            os: macos-latest
          - flask: '<3.1'
            os: macos-latest
          - flask: '<3.2'
            os: macos-latest
          - flask: '<2.2'
            os: windows-latest
          - flask: '<3.0'
            os: windows-latest
          - flask: '<3.1'
            os: windows-latest
          - flask: '<3.2'
            os: windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox tox-gh-actions
      - run: tox
        env:
          FLASK_VERSION: ${{ matrix.flask }}
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox tox-gh-actions
      - run: tox
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
